monte: random_number_generator Module Reference
random_number_generator Module Reference
Provides tools for sampling pseudo-random numbers.
Functions/Subroutines
subroutine, public initialize_rng ()
Initialize the random number generator.
double precision, public rand ()
Obtain a single random number.
Detailed Description
Provides tools for sampling pseudo-random numbers.
Author:
Jeremy Roberts
Note, this uses the Fortran intrinsic functions "random_seed" and "random_number". The implementation of these is compiler-specific. In particular, the gfortran implementation of random_number uses Marsaglia's "Keep It Simple Stupid" generator. While the implementation is thread safe, it is done in such a way that its parallel performance is really bad when heavily used (as we do in Monte Carlo). For parallel applications, a different generator is essential.
Function/Subroutine Documentation
subroutine,public random_number_generator::initialize_rng ()
Initialize the random number generator.
Definition at line 29 of file random_number_generator.f90.
Referenced by execute::run_problem().
double precision,public random_number_generator::rand ()
Obtain a single random number.
Returns:
random number
Definition at line 71 of file random_number_generator.f90.
Referenced by pdfs::get_collision_distance(), pdfs::get_collision_type(), pdfs::get_particle_mu(), pdfs::get_particle_pos(), and pdfs::get_scatter_mu().