monte: execute Module Reference
execute Module Reference
Main routines for running the problem.
Functions/Subroutines
subroutine run_problem ()
Run the simulation.
subroutine transport (n)
Perform transport of a single particle.
subroutine interaction ()
Determine and handle an interaction.
integer get_slab_id ()
Determine the slab in which a particle resides.
subroutine reset_tallies ()
Reset the tally array.
subroutine bank_tallies ()
Add the current tallies to the mean and variance.
subroutine print_tallies ()
Print the tally of each slab.
Detailed Description
Main routines for running the problem.
Author:
Bryan Herman
Function/Subroutine Documentation
subroutine execute::bank_tallies ()
Add the current tallies to the mean and variance.
Definition at line 241 of file execute.f90.
References tally::bank_tally(), global::geo, and global::tal.
Referenced by run_problem().
integer execute::get_slab_id ()
Determine the slab in which a particle resides.
Returns:
Slab ID
Definition at line 212 of file execute.f90.
References global::geo, and global::neutron.
Referenced by run_problem().
subroutine execute::interaction ()
Determine and handle an interaction.
Definition at line 175 of file execute.f90.
References pdfs::get_collision_type(), pdfs::get_scatter_mu(), global::mat, and global::neutron.
Referenced by run_problem().
subroutine execute::print_tallies ()
Print the tally of each slab.
Definition at line 260 of file execute.f90.
References global::geo, global::nhist, tally::perform_statistics(), and global::tal.
Referenced by main().
subroutine execute::reset_tallies ()
Reset the tally array.
Definition at line 223 of file execute.f90.
References global::geo, global::tal, and tally::tally_reset().
Referenced by run_problem().
subroutine execute::run_problem ()
Run the simulation.
Definition at line 25 of file execute.f90.
References bank_tallies(), global::geo, get_slab_id(), random_number_generator::initialize_rng(), interaction(), global::neutron, global::nhist, particle::particle_init(), reset_tallies(), and transport().
Referenced by main().
subroutine execute::transport (integer n)
Perform transport of a single particle.
Definition at line 83 of file execute.f90.
References global::geo, pdfs::get_collision_distance(), global::mat, global::neutron, and global::tal.
Referenced by run_problem().