monte: tally Module Reference
tally Module Reference
Provides routines for tallying particle interactions.
Data Types
type tally_type
A tally for a single slab region.
Functions/Subroutines
subroutine, public tally_reset (this)
Reset a tally.
subroutine, public bank_tally (this)
Reset a tally.
subroutine, public perform_statistics (this, n_hist, dx)
Compute the mean.
Detailed Description
Provides routines for tallying particle interactions.
Author:
Bryan Herman
Function/Subroutine Documentation
subroutine,public tally::bank_tally (type(tally_type) this)
Reset a tally.
Parameters:
[in] this A reference to a tally object
Definition at line 52 of file tally.f90.
Referenced by execute::bank_tallies().
subroutine,public tally::perform_statistics (type(tally_type),intent(inout) this, integer,intent(in) n_hist, double precision,intent(in) dx)
Compute the mean.
Parameters:
[in] this A reference to a tally object
[out] this A reference to a tally object
[in] n_hist Number of histories
[in] dx Slab width
Definition at line 70 of file tally.f90.
Referenced by execute::print_tallies().
subroutine,public tally::tally_reset (type(tally_type),intent(inout) this)
Reset a tally.
Parameters:
[in] this A reference to a tally object
Definition at line 39 of file tally.f90.
Referenced by execute::reset_tallies().