monte: global Module Reference
global Module Reference
Global data and problem allocation.
Functions/Subroutines
subroutine allocate_problem ()
Allocate the tallies.
subroutine free_memory ()
Free the tallies.
Variables
type(geometry_type) geo
define geometry
type(material_type) mat
define material
type(tally_type), dimension(:),
allocatable tal
define tally array
type(particle_type) neutron
define particle
integer nhist
number of particles to simulate
Detailed Description
Global data and problem allocation.
Author:
Bryan Herman
Function/Subroutine Documentation
subroutine global::allocate_problem ()
Allocate the tallies.
Definition at line 38 of file global.f90.
References geo, and tal.
Referenced by main().
subroutine global::free_memory ()
Free the tallies.
Definition at line 47 of file global.f90.
References tal.
Referenced by main().
Variable Documentation
type(geometry_type) global::geo
define geometry
Definition at line 19 of file global.f90.
Referenced by allocate_problem(), execute::bank_tallies(), execute::get_slab_id(), main(), execute::print_tallies(), execute::reset_tallies(), execute::run_problem(), and execute::transport().
type(material_type) global::mat
define material
Definition at line 22 of file global.f90.
Referenced by execute::interaction(), main(), and execute::transport().
type(particle_type) global::neutron
define particle
Definition at line 28 of file global.f90.
Referenced by execute::get_slab_id(), execute::interaction(), execute::run_problem(), and execute::transport().
integer global::nhist
number of particles to simulate
Definition at line 31 of file global.f90.
Referenced by main(), execute::print_tallies(), and execute::run_problem().
type(tally_type),dimension(:),allocatable global::tal
define tally array
Definition at line 25 of file global.f90.
Referenced by allocate_problem(), execute::bank_tallies(), free_memory(), execute::print_tallies(), execute::reset_tallies(), and execute::transport().