monte: particle Module Reference
particle Module Reference
Routines for defining and manipulating a particle.
Data Types
type particle_type
Defines a particle.
Functions/Subroutines
subroutine, public particle_init (this, L)
Initialize a particle.
Detailed Description
Routines for defining and manipulating a particle.
Author:
Bryan Herman
Function/Subroutine Documentation
subroutine,public particle::particle_init (type(particle_type),intent(inout) this, double precision,intent(in) L)
Initialize a particle.
Parameters:
[in] this A reference to a particle object
[in] L Total width of domain
Definition at line 34 of file particle.f90.
References pdfs::get_particle_mu(), and pdfs::get_particle_pos().
Referenced by execute::run_problem().