monte: random_number_generator_p Module Reference
random_number_generator_p Module Reference
Provides a simple implementation of the MCNP standard PRNG.
Functions/Subroutines
real(R8), public rand ()
Obtain a single 64 bit real pseudo random number.
subroutine, public initialize_rng (UserS, UserStride)
Initiates the random number generator for a new problem.
Variables
integer, parameter R8 = selected_real_kind(15, 307)
integer, parameter I8 = selected_int_kind(18)
integer(I8), save g = 19073486328125_I8
integer(I8), save c = 0_I8
integer(I8), save Stride = 152917_I8
integer(I8), save S0 = 19073486328125_I8
integer(I8), save TwoToMMinus1 = 281474976710655_I8
real(R8), save OneOver2toM = 1._R8 / 281474976710656._R8
integer(I8), save S = 19073486328125_I8
Detailed Description
Provides a simple implementation of the MCNP standard PRNG.
Author:
Jeremy Roberts
MCNP and most other Monte Carlo codes employ LCGs, defined by the relation
with the random number being defined
For the standard MCNP LCG,
and
(Recall that).
For parallel jobs, we have several options for RNs. We could let each process have its own (random?) starting seed, and then perform its batch of particle histories using its own sequence. This is not the best approach, since then the same problem run using different numbers of processes would yield different results, and we like reproducing results for debugging.
The solution: let each history have its own sequence of a certain length called the "stride". This works since any subset of the infinite sequence defined by the first two equations above should be random. To use this approach, we need a fast way to get any given . This is done by
which must use exact integer arithmetic. For the case that , we need only compute exactly. Brown gives the following algorithm:
     G = 1; h = g; i = modulo[k+2^m,2^m];
     do while (i .gt. 0 )
         if ( i is odd ) G = modulo[ G*h, 2^m ]
         h = modulo[ h^2 , 2^m ]
         i = floor(i/2)
     end
A similar algorithm exists for the other term. See the "Fundamentals..." notes for more.
It's worth pointing out use of the Fortran intrinsics "iand" and "btest" below. These are "bitwise and" and "bitwise test", respectively. To give a flavor...
   iand(1,2) compares [1000...] to [0100...] = 0
   iand(1,3) compares [1000...] to [1100...] = 0*2^0 + 1*2^1 ... = 2
and so on. A good exercise would be to show why
   S(k) = modulo[ (g^k*S(0)+c*(g^k-1)/(g-1), 2^M ]
        = iand( iand( g*S(0), 2^M-1 ) + c,  2^M-1 )
Hint: Show
   modulo[a+b,c] = modulo[modulo[a,c]+b,c]
Then show
   iand(a,c-1) = modulo(a,c)
when c is a power of 2.
References:
"THE MCNP5 RANDOM NUMBER GENERATOR", LA-UR-02-3782 http://mcnp-green.lanl.gov/publication/pdf/LA-UR-02-3782.pdf
"FUNDAMENTALS OF MONTE CARLO TRANSPORT", LA-UR-05-4983 http://...gov/publication/pdf/LA-UR-05-4983_Monte_Carlo_Lectures.pdf
Function/Subroutine Documentation
subroutine,public random_number_generator_p::initialize_rng (integer(I8),intent(in) UserS, integer(I8),intent(in) UserStride)
Initiates the random number generator for a new problem.
Warning: ONLY CALL THIS FROM THE MASTER THREAD!
Parameters:
[in] UserS Integer value of seed (default is 5^19)
[in] UserString Integer value of stride between histories
Definition at line 186 of file random_number_generator_p.f90.
References S, S0, and Stride.
real(R8),public random_number_generator_p::rand ()
Obtain a single 64 bit real pseudo random number.
Returns:
random number
Definition at line 128 of file random_number_generator_p.f90.
References c, g, OneOver2toM, S, and TwoToMMinus1.
Variable Documentation
integer(I8),save random_number_generator_p::c = 0_I8
Definition at line 110 of file random_number_generator_p.f90.
Referenced by rand().
integer(I8),save random_number_generator_p::g = 19073486328125_I8
Definition at line 109 of file random_number_generator_p.f90.
Referenced by rand().
integer,parameter random_number_generator_p::I8 = selected_int_kind(18)
Definition at line 101 of file random_number_generator_p.f90.
real(R8),save random_number_generator_p::OneOver2toM = 1._R8 / 281474976710656._R8
Definition at line 114 of file random_number_generator_p.f90.
Referenced by rand().
integer,parameter random_number_generator_p::R8 = selected_real_kind(15, 307)
Definition at line 100 of file random_number_generator_p.f90.
integer(I8),save random_number_generator_p::S = 19073486328125_I8
Definition at line 117 of file random_number_generator_p.f90.
Referenced by initialize_rng(), and rand().
integer(I8),save random_number_generator_p::S0 = 19073486328125_I8
Definition at line 112 of file random_number_generator_p.f90.
Referenced by initialize_rng().
integer(I8),save random_number_generator_p::Stride = 152917_I8
Definition at line 111 of file random_number_generator_p.f90.
Referenced by initialize_rng().
integer(I8),save random_number_generator_p::TwoToMMinus1 = 281474976710655_I8
Definition at line 113 of file random_number_generator_p.f90.
Referenced by rand().