monte: pdfs Module Reference
pdfs Module Reference
Routines for sampling various distributions.
Functions/Subroutines
double precision get_particle_pos (L)
Get a particle position in the slab.
double precision get_particle_mu ()
Sample the particle's direction (for the source).
double precision get_scatter_mu ()
Sample a particle's direction following a scattering event.
double precision get_collision_distance (xs)
Sample a particle's distance to next collision.
integer get_collision_type (absxs, scattxs, totxs)
Sample the type of collision a particle undergoes.
Detailed Description
Routines for sampling various distributions.
Author:
Bryan Herman
Note, all values are double precision, i.e. about 16 digits. We could use real's (about 8 digits), but what happens when we sample a billion times?
Function/Subroutine Documentation
double precision pdfs::get_collision_distance (double precision,intent(in) xs)
Sample a particle's distance to next collision.
This only applies to the slab with the given cross section. If the particles gets to a boundary, a new distance must be sampled with the appropriate cross section.
Parameters:
[in] xs The cross section of the slab traversed.
Returns:
The distance to be traveled.
Definition at line 74 of file pdfs.f90.
References random_number_generator::rand().
Referenced by execute::transport().
integer pdfs::get_collision_type (double precision,intent(in) absxs, double precision,intent(in) scattxs, double precision,intent(in) totxs)
Sample the type of collision a particle undergoes.
Cross sections are nothing but probabilities. If a particle can undergo either absorption or scattering, the probability of each is simply
and
respectively. Things get way more complicated in multigroup transport with multiple collision types. It's even worse for continuous energy treatments. Just ask Paul.
Parameters:
[in] absxs The cross section of the slab traversed.
[in] scattxs The cross section of the slab traversed.
[in] totxs The cross section of the slab traversed.
Returns:
The type of collision (1 for abs, 2 for scatter)
Definition at line 104 of file pdfs.f90.
References random_number_generator::rand().
Referenced by execute::interaction().
double precision pdfs::get_particle_mu ()
Sample the particle's direction (for the source).
This assumes an isotropic source in the LAB system.
Returns:
The particle's direction at birth.
Definition at line 41 of file pdfs.f90.
References random_number_generator::rand().
Referenced by particle::particle_init().
double precision pdfs::get_particle_pos (double precision,intent(in) L)
Get a particle position in the slab.
Parameters:
[in] L Total width of domain.
Returns:
A random location in the domain
Definition at line 25 of file pdfs.f90.
References random_number_generator::rand().
Referenced by particle::particle_init().
double precision pdfs::get_scatter_mu ()
Sample a particle's direction following a scattering event.
This assumes isotropic scattering in the LAB system.
Returns:
The particle's new direction.
Definition at line 56 of file pdfs.f90.
References random_number_generator::rand().
Referenced by execute::interaction().